### ISSUE TITLE
Missing Model Version

### ISSUE THREAD

**Issue by SteveCookTU** [PokeAPI/pokekotlin#49]
When trying to clean and package my own programs, it says the POM is invalid. After enabling debugging, it says the model version is missing. 

`<modelVersion>4.0.0</modelVersion>`

**Comment by sargunv** [comment]
What are you using to build your project? Is there a repo I can clone to try it out?

This might be a bug in Kobalt, the build tool I'm using. Will follow up with its developer.

**Comment by sargunv** [comment]
Kobalt has been updated. Will push a new version built with the new Kobalt tonight.

**Comment by sargunv** [comment]
Just released 2.2.4 with the fix.

**Comment by SteveCookTU** [comment]
Perfect! Thank you :)
