### ISSUE TITLE
ErrorResponse: (503) 

### ISSUE THREAD

**Issue by ijr84** [PokeAPI/pokekotlin#52]
The test in web give me:

Caused by: me.sargunvohra.lib.pokekotlin.client.ErrorResponse: (503) 

What's the problem?

Thanks.

**Comment by sargunv** [comment]
PokeApi is currently under DDoS protection, not an issue with this library. I'll leave this open until it's resolved though in case others come here with the same error.

**Comment by ijr84** [comment]
Thank you.

**Comment by sargunv** [comment]
There's some discussion about it on the PokeApi Slack channel. Currently we expect it to open back up sometime tomorrow.

**Comment by ijr84** [comment]
I'll read about it. Thanks.

**Comment by sekomod** [comment]
and I have same problem :( My App crash and can not catch the error.

**Comment by sargunv** [comment]
PokeAPI is open again today, this error should be gone now.
