### ISSUE TITLE
Crashes without internet

### ISSUE THREAD

**Issue by Advice-Dog** [PokeAPI/pokekotlin#57]
While using the example, I noticed that the code would crash my application if my device didn't have internet. There was also no callstack present. Should have some way to handle this case, and also something in the logging.

**Comment by sargunv** [comment]
Thanks for the report. Will look into it next week.

**Comment by sargunv** [comment]
Throwing an exception when there's no internet is intended. You should catch the exception and show an appropriate error message to the user. Could you tell me which exception you get?

**Comment by Advice-Dog** [comment]
I actually wasn't able to get any exception at all, there was no callstack given. Which sounds weird, right.

**Comment by Advice-Dog** [comment]
This is all I was able to see:
E/LOG: ║ Getting item for Pokedex.
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                               Process: com.app.poke, PID: 396

**Comment by sargunv** [comment]
Looks like Android is catching your exception from your AsyncTask and reporting the error. You'll need to put a try/catch in the AsyncTask.

**Comment by Advice-Dog** [comment]
Ok, I tried it a few more times.

Without a try catch, I did see an exception once ( Stream was closed ), but I just retried that and it went back to no exception again.

With a try/catch, it was able to catch it, but why am I unable to see that that call will throw an exception? Is it because of Kotlin?

**Comment by sargunv** [comment]
Yes, one of Kotlin's features is the lack of checked exceptions.

**Comment by Advice-Dog** [comment]
Alright. 

Would you mind updating the Java example to show how to get the network call off the main thread, and also to make sure people are aware that it can throw exceptions?

**Comment by sargunv** [comment]
Sure, will do. 
Created issue #58.

**Comment by pkill37** [comment]
I'm having the same issue with the Java example. I'm well versed in Java, but very new to Android.

I have:

- Installed dependencies
- Added `<uses-permission android:name="android.permission.INTERNET" />` to `AndroidManifest.xml`.
- Copy-pasted the example code to a fresh, empty activity:

```
PokeApi pokeApi = new PokeApiClient();
PokemonSpecies bulbasaur = pokeApi.getPokemonSpecies(1);
```

But the app still crashes and there's no stack trace to help me. Any help? @sargunster @Advice-Dog

**Comment by Advice-Dog** [comment]
Do you have internet? If not, then you need to make sure you try/catch the network call. Also make sure it's on another thread, as you can't do network calls on the main thread.

**Comment by pkill37** [comment]
I guess I should learn a bit more about Android first.  Indeed, there was a NetworkOnMainThreadException I didn't pay much attention to. I'm using AsyncTasks now to make the request in a worker thread. Thank you @Advice-Dog! 😄

**Comment by Advice-Dog** [comment]
No problems, good luck. 👍
