### ISSUE TITLE
Instant crash using the Java example

### ISSUE THREAD

**Issue by Vascosantos16** [PokeAPI/pokekotlin#61]
Hello!

I've been wanting to create a VGC companion app for quite a while and was thinking of doing so now.

I imported your API and tried your example code, but it instantly crashes with a network error.

Is there a fix for this? Because i can't find any.

PS: this happened on android studio.

**Comment by tdmalone** [comment]
Could you perhaps post the error? That might help with troubleshooting it ;)

**Comment by Vascosantos16** [comment]
https://pastebin.com/Gc4ESjZv

here you go my dude.

**Comment by Vascosantos16** [comment]
Any ideas?

**Comment by ianbenkenobi** [comment]
I have the exact same issue but in kotlin.

**Comment by Yoduh** [comment]
Networking operations can't be done on the main thread of your application.  You have to run it in an AsyncTask and add a permission to the AndroidManifest.xml file
see:
https://stackoverflow.com/a/6343299
