### ISSUE TITLE
Eclipse installation

### ISSUE THREAD

**Issue by B3tah3** [PokeAPI/pokekotlin#67]
Hi there! I'm trying to integrate this tool into my eclipse workspace but i cant find any guide and cant figure it out myself. I've copied all the files into a new Kotlin project and created a new Java class to run the test code provided in the readme. However, when i try to execute it, it return the Error:
 Exception in thread "main" java.lang.NoClassDefFoundError: me/sargunvohra/lib/pokekotlin/client/PokeApi
any idea what to do?

**Comment by sargunv** [comment]
I can't help you with specific IDEs. Use a build system like Gradle or Maven, and add the project's jitpack coordinates to your dependencies block there. 

https://docs.gradle.org/current/userguide/eclipse_plugin.html
